### PR TITLE
Kb/add arduino

### PR DESCRIPTION
**Pull request by KirkBoyd**
This is a pull request to finally bring the Arduino side of things into the main branch.

The main files we are concerned with are:
- leArm_1.1.2.ino
- drinkDuino.ino

The former runs on the Romeo and the latter runs on the Uno on the back.
There is still work to be done on each.
- drinkDuino needs
  - proper timing for actual drink distribution once new valves are in placed
  - maybe some ROS cleanup/optimization?

- leArm_1.1.2.ino needs
  - optimization on the logic sequence (seriously, it is a mess)
  - probably some cleanup on motion to make it look cooler when it moves the cup around
  - ROS cleanup/optimization; like switching to an action rather than publishers and subscribers

The other files are references/examples/previous attempts. Not too important.

### CODE REVIEW

**Review by isaiahCurtis — COMMENTED** [review]
Good job

**Review by KirkBoyd — COMMENTED** [review]
:thumbsup:

**Comment by jwhanson** [comment]
Great work!

We can pull this as a quick-n-dirty baseline for the "arduino" package but we discussed some architectural updates:
- We'll work together on moving to a more State-Machine like design for the arm loop logic, to reign in all the counters/timers/variables
- Want to add a "reset" connection (could be a ROS pub/sub for now) so that we can get back to a known state easily

I think we could drop things like the smoothing demo code and the learm 1.1.1 since we have our implementation, but if you'd like to have them for continuing development we can hold on to them for now.

**Comment by jwhanson** [comment]
Also: from a project structure perspective, I want to setup a ROS package that contains the launch files we currently have on the RPI. I think something like:
- arnie_bartender
    - arduino/ (arduino ino's)
    - launch/ (launch files for combined arm+dispenser system)

It's weird because there wouldn't be typical src files for this package, but it would help expose the combined arduino bartender functionality to other launch files.

Probably means we can drop the idea of the separate arnie_arm and arnie_dispenser pkgs, but I wouldn't mine keeping the arm package as just a place to play with the URDF and maybe get into some simulation if we find the time.

**Comment by KirkBoyd** [comment]
Had some small changes uncommitted.
@jwhanson if you can approve this then please just close the pull request and merge! Thanks!

**Review by jwhanson — APPROVED** [review]
Looking good, great job getting this working! Hoping we get the chance to do some of the clean up items from previous comments, but this is working and we're ready to pull it in.

**Pull request merged**
