### PR TITLE
Initial Registration GUI in PySide6

### PR DESCRIPTION
**Pull request by jwhanson**
I'm creating this pull request as an example for us to practice reviewing code.

I've gone through and implemented the registration pages in PySide6, but I haven't yet connected them to the DB.

### CODE REVIEW

**Comment by KirkBoyd** [comment]
looks good to me!

**Review by KirkBoyd — APPROVED** [review]
I say good

**Review by SteeleDove — APPROVED** [review]
Smart Man

**Review by drewim — COMMENTED** [review]
Looks good!

**Pull request merged**
